# Generated by Django 2.1.5 on 2019-08-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontype',
            name='dezo',
            field=models.CharField(default='fero', max_length=255),
            preserve_default=False,
        ),
    ]
