# Generated by Django 2.1.5 on 2019-08-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupontype_dezo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontype',
            name='minimum_order_value',
            field=models.IntegerField(default=0, verbose_name='minimum order value'),
        ),
        migrations.AddField(
            model_name='coupontype',
            name='name',
            field=models.CharField(default='fero', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
