# Generated by Django 2.1.5 on 2019-08-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20190802_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupontype',
            name='dezo',
        ),
        migrations.AddField(
            model_name='usedcoupon',
            name='coupon',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='used_coupons', to='coupon.Coupon'),
            preserve_default=False,
        ),
    ]
